"""Mail evidence workflow helpers for the FormOwl synthetic mail phase."""

from .candidates import (
    MailCandidateBridgeResult,
    extract_and_store_mail_candidates,
    extract_mail_semantics_and_candidates,
)
from .bundle import (
    EmailAttachment,
    EmailAttachmentOccurrence,
    EmailBodySegment,
    EmailMessage,
    EmailMessageOccurrence,
    EmbeddedMessageRelation,
    MailArchiveOccurrence,
    MailEvidenceBundle,
    MailFolderOccurrence,
    MailImportSession,
    MailParseRun,
    MailParseWarning,
    QuotedMessageCandidate,
    build_mail_evidence_bundle,
)
from .evidence import (
    MailBodySegment,
    MailEvidencePack,
    MailEvidencePackStore,
    MailEvidenceRecord,
    MailSearchResult,
    build_mail_evidence_pack,
    search_mail_evidence,
)
from .preflight import MailPreflightReadinessReview, build_mail_preflight_readiness_review
from .import_workflow import (
    MailUploadImportWorkflowResult,
    run_upload_session_mail_import,
    validate_mail_upload_import_summary,
)
from .upload_session import (
    MailUploadSessionTaskResult,
    build_mail_upload_session_handler,
    open_mail_upload_session,
    validate_mail_upload_session_task,
)
from .upload_surface import (
    MailUploadSurfaceReceipt,
    receive_mail_archive_upload,
    validate_mail_upload_surface_receipt,
)
from .upload_http import (
    MailUploadHttpSurfaceConfig,
    MailUploadHttpSurfacePostResult,
    build_mail_upload_http_surface_handler,
    create_mail_upload_http_surface_server,
    mail_upload_http_error_payload,
    receive_mail_archive_http_multipart,
    render_mail_upload_http_form,
    validate_mail_upload_http_post_result,
)
from .query import (
    MailEvidenceQueryGateway,
    MailEvidenceQueryResult,
    MailEvidenceReadResult,
    build_mail_evidence_query_handler,
    build_mail_evidence_read_handler,
)
from .postgres import (
    PostgreSQLMailEvidenceConnection,
    PostgreSQLMailEvidenceStore,
    build_postgre_sql_mail_evidence_query_handler,
    mail_evidence_postgre_sql_tables,
    mail_evidence_query_indexes,
    postgre_sql_mail_evidence_store_interfaces,
)
from .qa import (
    CaseProgressAnswer,
    CaseProgressItem,
    MailCaseProgressAnswerResult,
    MailCaseProgressGateway,
    build_case_progress_answer,
    build_mail_case_progress_handler,
)

__all__ = [
    "CaseProgressAnswer",
    "CaseProgressItem",
    "EmailAttachment",
    "EmailAttachmentOccurrence",
    "EmailBodySegment",
    "EmailMessage",
    "EmailMessageOccurrence",
    "EmbeddedMessageRelation",
    "MailBodySegment",
    "MailCandidateBridgeResult",
    "MailCaseProgressAnswerResult",
    "MailCaseProgressGateway",
    "MailArchiveOccurrence",
    "MailEvidenceBundle",
    "MailEvidencePack",
    "MailEvidencePackStore",
    "MailEvidenceQueryGateway",
    "MailEvidenceQueryResult",
    "MailEvidenceReadResult",
    "MailEvidenceRecord",
    "MailFolderOccurrence",
    "MailImportSession",
    "MailParseRun",
    "MailParseWarning",
    "MailPreflightReadinessReview",
    "MailSearchResult",
    "MailUploadImportWorkflowResult",
    "MailUploadHttpSurfaceConfig",
    "MailUploadHttpSurfacePostResult",
    "MailUploadSessionTaskResult",
    "MailUploadSurfaceReceipt",
    "PostgreSQLMailEvidenceConnection",
    "PostgreSQLMailEvidenceStore",
    "QuotedMessageCandidate",
    "build_case_progress_answer",
    "build_mail_case_progress_handler",
    "build_mail_evidence_bundle",
    "build_mail_evidence_pack",
    "build_mail_evidence_query_handler",
    "build_mail_evidence_read_handler",
    "build_mail_preflight_readiness_review",
    "build_mail_upload_http_surface_handler",
    "build_mail_upload_session_handler",
    "build_postgre_sql_mail_evidence_query_handler",
    "create_mail_upload_http_surface_server",
    "extract_and_store_mail_candidates",
    "extract_mail_semantics_and_candidates",
    "mail_evidence_postgre_sql_tables",
    "mail_evidence_query_indexes",
    "open_mail_upload_session",
    "postgre_sql_mail_evidence_store_interfaces",
    "mail_upload_http_error_payload",
    "receive_mail_archive_upload",
    "receive_mail_archive_http_multipart",
    "render_mail_upload_http_form",
    "run_upload_session_mail_import",
    "search_mail_evidence",
    "validate_mail_upload_http_post_result",
    "validate_mail_upload_import_summary",
    "validate_mail_upload_session_task",
    "validate_mail_upload_surface_receipt",
]
